### ISSUE TITLE
데모 영상 찍기

### ISSUE THREAD

**Issue by gomjellie** [woowa-techcamp-2021/cashbook-16#27]
## :hammer: 기능 설명

데모 영상을 만듭니다.

## 📑 체크리스트

> 수행해야 할 체크리스트

- [x] 줌 + 녹화기능으로 제작
- [x] JSX 만든것 예제 코드 + 실행
- [x] 프론트엔드 subscribe publish 구조 설명
- [x] 프론트엔드 라우터 설명
- [x] 디비 설계 + entity 설명

## 🚧 주의 사항

> 기능을 구현할 때 유의깊게 살펴볼 사항

없음

## 🕰 예상 시간

> 1 mh

**Comment by cothis** [comment]
완료 및 배포했습니다.
