### ISSUE TITLE
[BE] router - controller 분리 제안

### ISSUE THREAD

**Issue by hwookim** [woowa-techcamp-2021/cashbook-16#33]
## :hammer: 기능 설명

각 라우터의 api에 할당된 callback 함수를 분리하여 각 api의 역할을 명확하게 나타내도록 변경
[#19의 코드리뷰](https://github.com/woowa-techcamp-2021/cashbook-16/pull/19#pullrequestreview-718734562)

## 📑 체크리스트

> 수행해야 할 체크리스트

- [ ] 각 router의 callback 함수를 컨트롤러로 분리

## 🚧 주의 사항

> 기능을 구현할 때 유의깊게 살펴볼 사항

- 라우터의 역할을 드러낼 수 있는 네이밍을 한다

## 🕰 예상 시간

> N mh

**Comment by cothis** [comment]
backend 구조개발에서 진행할 것 같아요 감사합니다!

**Comment by gomjellie** [comment]
감사합니다~
피가되고 살이되는 고수 백엔드 개발자의 조언 새겨듣겠습니다
