### ISSUE TITLE
[FE] Tailwind.css 깃에서 추적해제

### ISSUE THREAD

**Issue by gomjellie** [woowa-techcamp-2021/cashbook-16#42]
## :hammer: 기능 설명

Tailwind.css 깃에서 추적해제

<img width="303" alt="image" src="https://user-images.githubusercontent.com/13645032/127791754-c7832492-4de4-41ec-a394-edd3bfba656a.png">

너무 크다.... 깃에 올리면 안되는거같음...

## 📑 체크리스트

> 수행해야 할 체크리스트

- [ ] tailwind.css 깃에서 추적 해제

## 🕰 예상 시간

> 5 mm

**Comment by cothis** [comment]
아하 이래서 내리신거구나
