### ISSUE TITLE
[Style] Pretendard 적용?

### ISSUE THREAD

**Issue by gomjellie** [woowa-techcamp-2021/cashbook-16#53]
## :hammer: 기능 설명

-apple-system 폰트에서 pretendard로 한번 바꿔보는건 어떨까요

글꼴은 의외로 중요해요.

https://github.com/orioncactus/pretendard

## 📑 체크리스트

> 수행해야 할 체크리스트

- [ ] 체크 사항 1
- [ ] 체크 사항 2
- [ ] 체크 사항 3
- [ ] 체크 사항 4

## 🚧 주의 사항

> 기능을 구현할 때 유의깊게 살펴볼 사항

- 주의 사항 1
- 주의 사항 2

## 🕰 예상 시간

> N mh

**Comment by cothis** [comment]
좋아요

**Comment by gomjellie** [comment]
적용완료
