### ISSUE TITLE
[BE] 데이터베이스 설계

### ISSUE THREAD

**Issue by cothis** [woowa-techcamp-2021/cashbook-16#9]
## :hammer: 기능 설명

기능 설명

Database ERD 

## 📑 체크리스트

> 수행해야 할 체크리스트

- [x] 요구사항 분석
- [x] ERD 설계

## 🚧 주의 사항

> 기능을 구현할 때 유의깊게 살펴볼 사항

- 관계 설정 잘하기
- 인덱스 설정 고민

**Comment by gomjellie** [comment]
끝!
